name: Build Aurorachat

on:
  push:
    branches: [ "main" ]
    paths:
      - 'source/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'source/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/cool-guy-awesome/devkitarm-wine-docker:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          make
          make cia

      - name: Upload 3DSX
        uses: actions/upload-artifact@v4
        with:
          name: aurorachat 3DSX Automatic Build (could be unfinished!)
          path: ./aurorachat.3dsx
        
      - name: Upload CIA 
        uses: actions/upload-artifact@v4
        with:
          name: aurorachat CIA Automatic Build (could be unfinished!)
          path: ./aurorachat.cia
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: zulu
          java-version: '21'
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5.1.0
        with:
          dotnet-version: 8.0
